
server:
  port: 7070
 
  servlet:
    context-path: /redis-admin
    
spring:
  profiles:
    active:
    - dev
  #resources:
   # static-locations:
   # - /view/**
  mvc: 
    #static-path-pattern: /view/**
    #view:
      #prefix: /view/
      #suffix: .jsp
    favicon:
      enabled: true

  autoconfigure:
    exclude:
    - 

  http:
    log-request-details: true

# spring.devtools.restart.enabled 禁用devtools自动重启功能，直接用IDE的热部署
  devtools:
    restart:
      enabled: true
      additional-paths:
      - src/main/java

# 管理员帐号密码
manager: 
  username: admin
  password: admin










